apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
#  - datasciencecluster.yaml
  - dsc-init.yaml

patches:
  - path: patch-datasciencecluster.yaml
    target:
      kind: DataScienceCluster
  - path: patch-dsc-init.yaml
    target:
      kind: DSCInitialization
      
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
# # components:
# #   - ../wait-for-servicemesh