---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/instance: minio
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  
resources:
  - namespace.yaml
  - service.yaml
  - secret.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - route-api.yaml
  - route-ui.yaml
  
