kind: Deployment
apiVersion: apps/v1
metadata:
  name: elastic-granite-chat
  namespace: elastic-granite-chat
  labels:
    app: elastic-granite-chat
    app.kubernetes.io/component: elastic-granite-chat
    app.kubernetes.io/instance: elastic-granite-chat
    app.kubernetes.io/name: elastic-granite-chat
    app.kubernetes.io/part-of: elastic-granite-chat-app
    app.openshift.io/runtime-namespace: elastic-granite-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-granite-chat
  template:
    metadata:
      labels:
        app: elastic-granite-chat
        deployment: elastic-granite-chat
    spec:
      containers:
        - name: elastic-granite-chat
          image: 'podman pull quay.io/ilago/elastic-granite-chat'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8501
              protocol: TCP
          env:
            - name: MODEL_ENDPOINT
              value: '<OPENSHIFT_AI_MODEL_INFERENCE_ENDPOINT>'
            - name: ELASTIC_URL
              value: 'https://<YOUR_ELASTICSEARCH_SERVICE_URL>:9200'
            - name: ELASTIC_PASS
              value: '<YOUR_ELASTICSEARCH_PASSWORD>'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: elastic-granite-chat
  namespace: elastic-granite-chat
  labels:
    app: elastic-granite-chat
    app.kubernetes.io/component: elastic-granite-chat
    app.kubernetes.io/instance: elastic-granite-chat
    app.kubernetes.io/name: elastic-granite-chat
    app.kubernetes.io/part-of: elastic-granite-chat-app
    app.openshift.io/runtime-version: latest
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8501-tcp
      protocol: TCP
      port: 8501
      targetPort: 8501
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: elastic-granite-chat
    deployment: elastic-granite-chat
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: elastic-granite-chat
  namespace: elastic-granite-chat
  labels:
    app: elastic-granite-chat
    app.kubernetes.io/component: elastic-granite-chat
    app.kubernetes.io/instance: elastic-granite-chat
    app.kubernetes.io/name: elastic-granite-chat
    app.kubernetes.io/part-of: elastic-granite-chat-app
    app.openshift.io/runtime-version: latest
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: elastic-granite-chat
    weight: 100
  port:
    targetPort: 8501-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
