---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/instance: pre-requisites
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  
resources:

  # Support for GPU Acceleration
#  - operator-nfd
#  - operator-nvidia-gpu

  # KServe Installation for Single-model server
  - operator-serverless
  - operator-servicemesh
  
  # Support for authentication of server models
  - operator-authorino