---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: elastic-granite-chat-spanish
  namespace: elastic-granite-chat-spanish
  labels:
    app: elastic-granite-chat-spanish
    app.kubernetes.io/component: elastic-granite-chat-spanish
    app.kubernetes.io/instance: elastic-granite-chat-spanish
    app.kubernetes.io/name: elastic-granite-chat-spanish
    app.kubernetes.io/part-of: elastic-granite-chat-spanish-app
    app.openshift.io/runtime-namespace: elastic-granite-chat-spanish
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-granite-chat-spanish
  template:
    metadata:
      labels:
        app: elastic-granite-chat-spanish
        deployment: elastic-granite-chat-spanish
    spec:
      containers:
        - name: elastic-granite-chat-spanish
          image: 'quay.io/ilago/elastic-granite3.2b-chat:spanish'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8501
              protocol: TCP
          env:
            - name: MODEL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: environment-variables
                  key: MODEL_ENDPOINT
            - name: ELASTIC_URL
              valueFrom:
                configMapKeyRef:
                  name: environment-variables
                  key: ELASTIC_URL
            - name: ELASTIC_PASS
              valueFrom:
                configMapKeyRef:
                  name: environment-variables
                  key: ELASTIC_PASS
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600