---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knative-serving
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - knative-serving-instance.yaml
  - namespace.yaml
