apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: elasticsearch-eck-operator-certified
  namespace: elastic-vectordb
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec: {}